services:
  postgres:
    image: postgres:16.1
    container_name: stock-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: stock-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER" ]
      timeout: 5s
      interval: 5s
      retries: 10

  account-service:
    image: account-service
    container_name: account-service
    ports:
      - "9191:9191"

  crm-service:
    image: crm-service
    container_name: crm-service
    ports:
      - "9292:9292"

  exchangerate-service:
    image: exchangerate-service
    container_name: exchangerate-service
    ports:
      - "9090:9090"