spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: keep-stock
  profiles:
    active: default
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5433/stock-db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

s3:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: product-bucket

app:
  scheduling:
    mode: none
    period: 6000000000
    priceIncreasePercentage: 10.1
    exclusiveLock: true
  exchange-rate-file:
    path: src/main/resources/exchange-rate.json
  exchange-rate:
    host: http://localhost:9090
    methods:
      get-actual-rate: /api/v1/exchange-rates
  account-service:
    host: http://localhost:9191
    methods:
      get-accounts: /api/v1/account
  crm-service:
    host: http://localhost:9292
    methods:
      get-customer-inns: /api/v1/account/inns
  currency-service:
    model: work
  kafka:
    enabled: true

kafka:
  bootstrapAddress: http://localhost:9092
  groupId: keep-stock-group

logging:
  level:
    com.example: info
    org.hibernate.SQL: error
    org:
      springframework:
        orm.jpa: error
        transaction: error
        transaction.interceptor: error
        orm.jpa.JpaTransactionManager: error
        web: info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
