spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: keep-stock
  profiles:
    active: default
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5433/stock-db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

s3:
  endpoint: ${S3_ENDPOINT}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket: product-bucket

app:
  scheduling:
    mode: none
    period: 6000000000
    priceIncreasePercentage: 10.1
    exclusiveLock: true
  exchange-rate-file:
    path: ${APP_EXCHANGE_RATE_FILE}
  exchange-rate:
    host: ${APP_EXCHANGE_RATE_HOST}
    methods:
      get-actual-rate: /api/v1/exchange-rates
  account-service:
    host: ${APP_ACCOUNT_SERVICE_HOST}
    methods:
      get-accounts: /api/v1/account
  crm-service:
    host: ${APP_CRM_SERVICE_HOST}
    methods:
      get-customer-inns: /api/v1/account/inns
  currency-service:
    model: work
  kafka:
    enabled: true

kafka:
  bootstrapAddress: http://localhost:9092
  groupId: keep-stock-group

logging:
  level:
    com.example: info
    org.hibernate.SQL: error
    org:
      springframework:
        orm.jpa: error
        transaction: error
        transaction.interceptor: error
        orm.jpa.JpaTransactionManager: error
        web: info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  address: 0.0.0.0
